"use client"

import { Copy, RotateCcw, LogOut, Settings } from "lucide-react"
import { useCalculator, formatCurrency } from "@/lib/calculator-store"
import { SubscriptionStatus } from "./subscription-status"
import { SubscriptionModal } from "./subscription-modal"
import { useState, useEffect } from "react"
import { useAuth } from "@/lib/auth-hooks"
import Link from "next/link"

export function Navbar() {
  const { state, updateState, resetState, results } = useCalculator()
  const { user, logout } = useAuth()
  const [showToast, setShowToast] = useState(false)
  const [showAuthMenu, setShowAuthMenu] = useState(false)
  const [showUpgradeModal, setShowUpgradeModal] = useState(false)

  const fetchExchangeRate = async () => {
    try {
      const res = await fetch("https://open.er-api.com/v6/latest/USD")
      const data = await res.json()
      if (data.rates && data.rates.KES) {
        updateState({ exchangeRate: parseFloat(data.rates.KES.toFixed(2)) })
      }
    } catch {
      // Keep manual rate if fetch fails
    }
  }

  useEffect(() => {
    if (state.isUsdMode) {
      fetchExchangeRate()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state.isUsdMode])

  const toggleUsdMode = () => {
    updateState({ isUsdMode: !state.isUsdMode })
  }

  const copyReport = () => {
    const summary = `
PRODUCT IMPORTS PROFIT OS - REPORT
-----------------------------------
Item: ${state.itemName || "N/A"}
Qty: ${state.quantity} units
Method: ${state.shippingMethod}

Net Profit: KES ${formatCurrency(results.netProfit)}
Margin: ${results.margin.toFixed(1)}%
Break-even: KES ${formatCurrency(results.breakEven)}/unit

Sales Total: KES ${formatCurrency(results.totalSales)}
Inventory: KES ${formatCurrency(results.totalBuying)}
Shipping: KES ${formatCurrency(results.totalShipping)}
----------------------------
Generated by Product Imports Profit OS
    `.trim()

    navigator.clipboard.writeText(summary)
    setShowToast(true)
    setTimeout(() => setShowToast(false), 2000)
  }

  return (
    <>
      <nav className="sticky top-0 z-50 border-b border-slate-100 bg-white/95 backdrop-blur-lg px-4 sm:px-6 py-2 sm:py-3 shadow-sm">
        <div className="max-w-7xl mx-auto flex flex-row justify-between items-center gap-2 sm:gap-4">
          <div className="flex items-center gap-2 sm:gap-3 min-w-0">
            <div className="w-7 sm:w-10 h-7 sm:h-10 bg-orange-600 rounded-lg sm:rounded-xl flex items-center justify-center shadow-lg shadow-orange-200 flex-shrink-0">
              <svg
                viewBox="0 0 24 24"
                className="w-4 sm:w-6 h-4 sm:h-6 text-white fill-none stroke-current"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M12 2L2 7l10 5 10-5-10-5z" />
                <path d="M2 17l10 5 10-5" />
                <path d="M2 12l10 5 10-5" />
              </svg>
            </div>
            <div className="hidden sm:block">
              {user ? (
                <>
                  <h1 className="text-lg sm:text-xl font-extrabold tracking-tight text-slate-800 leading-none">
                    P.I.P.OS
                  </h1>
                  <p className="text-[9px] sm:text-[10px] font-bold text-orange-600 tracking-widest mt-0.5">
                    know your profit before you import
                  </p>
                </>
              ) : (
                <>
                  <h1 className="text-lg sm:text-xl font-extrabold tracking-tight text-slate-800 leading-none">
                    PRODUCT IMPORTS PROFIT OS
                  </h1>
                  <p className="text-[9px] sm:text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-0.5">
                    Smart Import Engine v4.0
                  </p>
                </>
              )}
            </div>
            <div className="sm:hidden">
              {user ? (
                <div>
                  <h1 className="text-xs font-extrabold tracking-tight text-slate-800 leading-tight">
                    P.I.P.OS
                  </h1>
                  <p className="text-[7px] font-bold text-orange-600 tracking-tight leading-tight mt-0.5">
                    know your profit<br />before you import
                  </p>
                </div>
              ) : (
                <h1 className="text-xs font-extrabold tracking-tight text-slate-800 leading-tight">
                  PROFIT<br />OS
                </h1>
              )}
            </div>
          </div>

          <div className="flex items-center gap-2 sm:gap-6 flex-wrap justify-center sm:justify-end">
            {/* Currency Control */}
            <div className="hidden sm:flex items-center gap-3 px-4 py-2 bg-slate-100 rounded-full border border-slate-200">
              <span className="text-[10px] font-black text-slate-500 tracking-tighter">
                USD SOURCE
              </span>
              <button
                onClick={toggleUsdMode}
                className={`relative w-11 h-[22px] rounded-full transition-colors ${
                  state.isUsdMode ? "bg-orange-500" : "bg-slate-300"
                }`}
                aria-label="Toggle USD mode"
              >
                <span
                  className={`absolute top-[3px] left-[3px] w-4 h-4 bg-white rounded-full shadow-sm transition-transform ${
                    state.isUsdMode ? "translate-x-[22px]" : ""
                  }`}
                />
              </button>
            </div>

            {/* Mobile currency toggle - smaller */}
            <button
              onClick={toggleUsdMode}
              className={`sm:hidden p-1.5 rounded-md text-xs font-bold transition-all ${
                state.isUsdMode ? "bg-orange-500 text-white" : "bg-slate-100 text-slate-600"
              }`}
              aria-label="Toggle USD mode"
              title="USD"
            >
              USD
            </button>

            <div className="hidden sm:block h-5 w-px bg-slate-200" />

            {user && (
              <>
                <div className="hidden sm:block">
                  <SubscriptionStatus onClick={() => setShowUpgradeModal(true)} />
                  <SubscriptionModal 
                    isOpen={showUpgradeModal} 
                    onClose={() => setShowUpgradeModal(false)}
                  />
                </div>
              </>
            )}

            <div className="hidden sm:block h-6 w-px bg-slate-200" />

            <div className="flex gap-1 sm:gap-2">
              <button
                onClick={resetState}
                className="p-1.5 sm:p-2.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-md sm:rounded-lg transition-all"
                aria-label="Reset calculator"
              >
                <RotateCcw className="w-3.5 sm:w-5 h-3.5 sm:h-5" />
              </button>
              <button
                onClick={copyReport}
                className="hidden sm:flex items-center gap-2 px-5 py-2.5 bg-slate-900 text-white rounded-xl font-bold text-sm hover:bg-slate-800 transition-all shadow-lg shadow-slate-200"
              >
                <span>Copy Report</span>
                <Copy className="w-4 h-4" />
              </button>

              {/* Mobile copy button */}
              <button
                onClick={copyReport}
                className="sm:hidden p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-md transition-all"
                aria-label="Copy Report"
              >
                <Copy className="w-3.5 h-3.5" />
              </button>

              <div className="hidden sm:block h-5 w-px bg-slate-200" />

              {/* Auth Menu */}
              {user ? (
                <div className="relative">
                  <button
                    onClick={() => setShowAuthMenu(!showAuthMenu)}
                    className="flex items-center gap-2 px-1.5 sm:px-4 py-1.5 sm:py-2 text-xs sm:text-sm font-bold text-slate-700 hover:bg-slate-100 rounded-md sm:rounded-lg transition-all"
                  >
                    <span className="hidden sm:inline">{user.email?.split('@')[0]}</span>
                    <span className="sm:hidden text-lg">⚙️</span>
                  </button>
                  {showAuthMenu && (
                    <div className="absolute right-0 mt-2 w-48 bg-white rounded-xl shadow-xl border border-slate-200 z-50">
                      <div className="p-3 border-b border-slate-200">
                        <p className="text-xs text-slate-500">Signed in as</p>
                        <p className="text-sm font-bold text-slate-900 truncate">{user.email}</p>
                      </div>
                      <button
                        onClick={() => {
                          logout()
                          setShowAuthMenu(false)
                        }}
                        className="w-full flex items-center gap-2 px-4 py-3 text-sm font-bold text-slate-700 hover:bg-slate-100 transition-all"
                      >
                        <LogOut className="w-4 h-4" />
                        Sign Out
                      </button>
                    </div>
                  )}
                </div>
              ) : (
                <Link
                  href="/auth/login"
                  className="px-4 py-2 sm:px-5 sm:py-2.5 bg-blue-500 text-white rounded-lg sm:rounded-xl font-bold text-xs sm:text-sm hover:bg-blue-600 transition-all whitespace-nowrap"
                >
                  Sign In
                </Link>
              )}
            </div>
          </div>
        </div>
      </nav>

      {/* Toast */}
      <div
        className={`fixed bottom-10 left-1/2 -translate-x-1/2 px-8 py-4 bg-slate-900 text-white rounded-2xl shadow-2xl font-bold text-sm tracking-wide transition-all z-[100] ${
          showToast
            ? "opacity-100 -translate-y-2.5"
            : "opacity-0 pointer-events-none"
        }`}
      >
        Report Copied to Clipboard
      </div>
    </>
  )
}
